include(core/inc/common.inc)

CREATE TABLE CORE.CLASSES
(
 ID          CORE.D_OBJECT_CLASS NOT NULL,
 NAME        CORE.D_CLASS_NAME_NN_UCASE,
 TABLE_ID    CORE.D_TABLE_ID NOT NULL,
 SEQ_SCHEMA  CORE.D_DBOBJ_NAME,
 SEQ_NAME    CORE.D_DBOBJ_NAME,
 DESCRIPTION VARCHAR (128),
 
 CONSTRAINT PK_CLASSES PRIMARY KEY (ID),

 UNIQUE (NAME),

 FOREIGN KEY (TABLE_ID) REFERENCES CORE.TABLE_NAMES (ID),
 
 CONSTRAINT M4_CONCAT(CHECK_CLASSES_SEQUENCE_ID)
  CHECK((SEQ_SCHEMA IS NULL) OR (SEQ_NAME IS NOT NULL))
);/*TABLE CORE.CLASSES*/
