include(common/inc/common.inc)

/* ********************************************************************************************** */

/*reserve first 199 ids*/
CREATE SEQUENCE COMMON.SEQ_CURRENCIES START WITH 200;

CREATE TABLE COMMON.CURRENCIES
(
 OBJECT_ID     CORE.D_OBJECT_ID NOT NULL,
 OBJECT_CLASS  CORE.D_OBJECT_CLASS NOT NULL,

 NAME          COMMON.D_CURRENCY_NAME_NN,
 SHORT_NAME    COMMON.D_CURRENCY_SHORT_NAME_NN_UCASE,

 /* ---------- */
 M4_DEF_OBJECT_PK(COMMON_CURRENCIES),

 M4_DEF_OBJECT_FK(COMMON_CURRENCIES,CORE_OBJECTS),
 
 CONSTRAINT M4_CONCAT(UNIQUE_, TBLID_COMMON_CURRENCIES, __short_name)
  UNIQUE(SHORT_NAME,OBJECT_CLASS)
);/*TABLE COMMON.CURRENCIES*/

M4_CREATE_TRIGGER_OBJ_DELETE(COMMON_CURRENCIES);

M4_REG_TABLE_NAME2(COMMON_CURRENCIES,CORE_OBJECTS);

M4_REG_CLASS2(COMMON_CURRENCIES,COMMON_CURRENCIES,'seq_currencies','Валюта');

M4_REG_POS_OBJ_LINKS(CORE_OBJECTS,COMMON_CURRENCIES);

M4_CREATE_TRIGGER_RO_OBJ_GUARD(COMMON_CURRENCIES);

/* ********************************************************************************************** */
