include(common/inc/common.inc)

/* ********************************************************************************************** */

/*reserve first 999 ids*/
CREATE SEQUENCE COMMON.SEQ_CUSTOMERS START WITH 1000;

CREATE TABLE COMMON.CUSTOMERS
(
 OBJECT_ID     CORE.D_OBJECT_ID NOT NULL,
 OBJECT_CLASS  CORE.D_OBJECT_CLASS NOT NULL,

 NAME          COMMON.D_CUSTOMER_NAME_NN,
 LOGIN         COMMON.D_CUSTOMER_LOGIN_NN,
 PSWD_MD5      COMMON.D_MD5_CODE NOT NULL,

 STATE         COMMON.D_CUSTOMER_STATE_ID NOT NULL,
 
 /* ---------- */
 M4_DEF_OBJECT_PK(COMMON_CUSTOMERS),

 M4_DEF_OBJECT_FK(COMMON_CUSTOMERS,CORE_OBJECTS),

 CONSTRAINT M4_CONCAT(UNIQUE_, TBLID_COMMON_CUSTOMERS, __login)
  UNIQUE(LOGIN,OBJECT_CLASS),
 
 CONSTRAINT M4_CONCAT(FK_, TBLID_COMMON_CUSTOMERS, __state)
  FOREIGN KEY (STATE) REFERENCES COMMON.TYPE_CUSTOMER_STATES (ID)
);/*TABLE COMMON.CUSTOMERS*/

M4_CREATE_TRIGGER_OBJ_DELETE(COMMON_CUSTOMERS);

M4_REG_TABLE_NAME2(COMMON_CUSTOMERS,CORE_OBJECTS);

M4_REG_CLASS2(COMMON_CUSTOMERS,COMMON_CUSTOMERS,'seq_customers','Пользователь');

M4_REG_POS_OBJ_LINKS(CORE_OBJECTS,COMMON_CUSTOMERS);

M4_CREATE_TRIGGER_RO_OBJ_GUARD(COMMON_CUSTOMERS);

/* ********************************************************************************************** */

/*TEST: 123*/

INSERT INTO TBLNAME_CORE_OBJECTS
 (OBJECT_ID,
  OBJECT_CLASS,
  OWNER_ID,
  OWNER_CLASS)
VALUES
 (1,
  CLASSID_COMMON_CUSTOMERS,
  0,
  CLASSID_CORE_OBJECTS);

INSERT INTO TBLNAME_COMMON_CUSTOMERS
 (OBJECT_ID,
  OBJECT_CLASS,
  NAME,
  LOGIN,
  PSWD_MD5,
  STATE)
VALUES
 (1,
  CLASSID_COMMON_CUSTOMERS,
  'Built-in test account',
  'Test',
  '202cb962ac59075b964b07152d234b70',
  C_COMMON_EMPLOYER_STATE_ID__ACTIVE);

/* ********************************************************************************************** */
