define([[TBLID_CRYPTOBOT_COINS]],[[3010]])
define([[TBLNAME_CRYPTOBOT_COINS]],[[cryptobot.coins]])

define([[TABLE_SCHEMA__CRYPTOBOT_COINS]],[[cryptobot]])
define([[TABLE_NAME__CRYPTOBOT_COINS]],[[coins]])

/* ------------------------------------ */
define([[TBLID_CRYPTOBOT_MARKETS]],[[3011]])
define([[TBLNAME_CRYPTOBOT_MARKETS]],[[cryptobot.markets]])

define([[TABLE_SCHEMA__CRYPTOBOT_MARKETS]],[[cryptobot]])
define([[TABLE_NAME__CRYPTOBOT_MARKETS]],[[markets]])

/* ------------------------------------ */
define([[TBLID_CRYPTOBOT_PRICES]],[[3012]])
define([[TBLNAME_CRYPTOBOT_PRICES]],[[cryptobot.prices]])

define([[TABLE_SCHEMA__CRYPTOBOT_PRICES]],[[cryptobot]])
define([[TABLE_NAME__CRYPTOBOT_PRICES]],[[prices]])

/* ------------------------------------ */
define([[TBLID_CRYPTOBOT_PRICES_HISTORY]],[[3013]])
define([[TBLNAME_CRYPTOBOT_PRICES_HISTORY]],[[cryptobot.prices_history]])

define([[TABLE_SCHEMA__CRYPTOBOT_PRICES_HISTORY]],[[cryptobot]])
define([[TABLE_NAME__CRYPTOBOT_PRICES_HISTORY]],[[prices_history]])

/* ------------------------------------ */
define([[TBLID_CRYPTOBOT_MARKETS_ITEMS_NAMES]],[[3014]])
define([[TBLNAME_CRYPTOBOT_MARKETS_ITEMS_NAMES]],[[cryptobot.markets_items_names]])

define([[TABLE_SCHEMA__CRYPTOBOT_MARKETS_ITEMS_NAMES]],[[cryptobot]])
define([[TABLE_NAME__CRYPTOBOT_MARKETS_ITEMS_NAMES]],[[markets_items_names]])

/* ------------------------------------ */
define([[TBLID_CRYPTOBOT_AMOUNTS_HISTORY]],[[3015]])
define([[TBLNAME_CRYPTOBOT_AMOUNTS_HISTORY]],[[cryptobot.amounts_history]])

define([[TABLE_SCHEMA__CRYPTOBOT_AMOUNTS_HISTORY]],[[cryptobot]])
define([[TABLE_NAME__CRYPTOBOT_AMOUNTS_HISTORY]],[[amounts_history]])
