include(core/inc/common.inc)
include(common/inc/table_ids.inc)
include(common/inc/classes.inc)

/* ********************************************************************************************** */

define([[C_COMMON_EMPLOYER_STATE_ID__NOT_ACTIVATED]],[[0]])
define([[C_COMMON_EMPLOYER_STATE_ID__ACTIVE]],[[1]])
define([[C_COMMON_EMPLOYER_STATE_ID__DISABLED]],[[2]])

/* ********************************************************************************************** */
