define([[TBLID_COMMON_EMPLOYEE]],[[1010]])
define([[TBLNAME_COMMON_EMPLOYEE]],[[common.employee]])

define([[TABLE_SCHEMA__COMMON_EMPLOYEE]],[[common]])
define([[TABLE_NAME__COMMON_EMPLOYEE]],[[employee]])

/* ------------------------------------ */
define([[TBLID_COMMON_CURRENCIES]],[[1011]])
define([[TBLNAME_COMMON_CURRENCIES]],[[common.currencies]])

define([[TABLE_SCHEMA__COMMON_CURRENCIES]],[[common]])
define([[TABLE_NAME__COMMON_CURRENCIES]],[[currencies]])

/* ------------------------------------ */
define([[TBLID_COMMON_CUSTOMERS]],[[1012]])
define([[TBLNAME_COMMON_CUSTOMERS]],[[common.customers]])

define([[TABLE_SCHEMA__COMMON_CUSTOMERS]],[[common]])
define([[TABLE_NAME__COMMON_CUSTOMERS]],[[customers]])

/* ------------------------------------ */
define([[TBLID_TYPE_CUSTOMER_STATES]],[[1013]])
define([[TBLNAME_TYPE_CUSTOMER_STATES]],[[common.type_customer_states]])

define([[TABLE_SCHEMA__TYPE_CUSTOMER_STATES]],[[common]])
define([[TABLE_NAME__TYPE_CUSTOMER_STATES]],[[type_customer_states]])

/* ------------------------------------ */
define([[TBLID_COMMON_ROBOTS]],[[1014]])
define([[TBLNAME_COMMON_ROBOTS]],[[common.robots]])

define([[TABLE_SCHEMA__COMMON_ROBOTS]],[[common]])
define([[TABLE_NAME__COMMON_ROBOTS]],[[robots]])

/* ------------------------------------ */
