include(cryptobot/inc/common.inc)

/* ********************************************************************************************** */

/*reserve first 999 ids*/
CREATE SEQUENCE CRYPTOBOT.SEQ_MARKETS START WITH 1000;

CREATE TABLE CRYPTOBOT.MARKETS
(
 OBJECT_ID     CORE.D_OBJECT_ID NOT NULL,
 OBJECT_CLASS  CORE.D_OBJECT_CLASS NOT NULL,

 NAME          CRYPTOBOT.D_MARKET_NAME_NN,
 SHORT_NAME    CRYPTOBOT.D_MARKET_SHORT_NAME_NN_UCASE,

 /* ---------- */
 M4_DEF_OBJECT_PK(CRYPTOBOT_MARKETS),

 M4_DEF_OBJECT_FK(CRYPTOBOT_MARKETS,CORE_OBJECTS),

 CONSTRAINT M4_CONCAT(UNIQUE_, TBLID_CRYPTOBOT_MARKETS, __short_name)
  UNIQUE(SHORT_NAME,OBJECT_CLASS)
);/*TABLE CRYPTOBOT.MARKETS*/

M4_CREATE_TRIGGER_OBJ_DELETE(CRYPTOBOT_MARKETS);

M4_REG_TABLE_NAME2(CRYPTOBOT_MARKETS,CORE_OBJECTS);

M4_REG_CLASS2(CRYPTOBOT_MARKETS,CRYPTOBOT_MARKETS,'seq_markets','Торговая площадка (биржа)');

M4_REG_POS_OBJ_LINKS(CORE_OBJECTS,CRYPTOBOT_MARKETS);

M4_CREATE_TRIGGER_RO_OBJ_GUARD(CRYPTOBOT_MARKETS);

/* ********************************************************************************************** */
