include(cryptobot/inc/common.inc)

/* ********************************************************************************************** */

/*reserve first 99 ids*/
CREATE SEQUENCE CRYPTOBOT.SEQ_MARKETS_ITEMS_NAMES START WITH 100;

CREATE TABLE CRYPTOBOT.MARKETS_ITEMS_NAMES
(
 OBJECT_ID       CORE.D_OBJECT_ID NOT NULL,
 OBJECT_CLASS    CORE.D_OBJECT_CLASS NOT NULL,

 MARKET_ID       CORE.D_OBJECT_ID NOT NULL,
 MARKET_CLASS    CORE.D_OBJECT_CLASS NOT NULL,

 ITEM_ID         CORE.D_OBJECT_ID NOT NULL,
 ITEM_CLASS      CORE.D_OBJECT_CLASS NOT NULL,

 ITEM_NAME       CRYPTOBOT.D_MARKET_ITEM_NAME_NN,
 ITEM_SHORT_NAME CRYPTOBOT.D_MARKET_ITEM_SHORT_NAME_NN,

 /* ---------- */
 M4_DEF_OBJECT_PK(CRYPTOBOT_MARKETS_ITEMS_NAMES),

 M4_DEF_OBJECT_FK(CRYPTOBOT_MARKETS_ITEMS_NAMES,CORE_OBJECTS),

 CONSTRAINT M4_CONCAT(FK_, TBLID_CRYPTOBOT_MARKETS_ITEMS_NAMES, _, TBLID_CORE_OBJECTS, __BY_MARKET)
  FOREIGN KEY (MARKET_ID,MARKET_CLASS) REFERENCES TBLNAME_CORE_OBJECTS (OBJECT_ID,OBJECT_CLASS),

 CONSTRAINT M4_CONCAT(FK_, TBLID_CRYPTOBOT_MARKETS_ITEMS_NAMES, _, TBLID_CORE_OBJECTS, __BY_ITEM)
  FOREIGN KEY (ITEM_ID,ITEM_CLASS) REFERENCES TBLNAME_CORE_OBJECTS (OBJECT_ID,OBJECT_CLASS),

 /*пока мы не будем разрешать указание нескольких имен для одного и того же объекта в рамках одного маркета*/
 CONSTRAINT UNIQUE_OF_MARKET_ITEM_REF
  UNIQUE(MARKET_ID,MARKET_CLASS,ITEM_ID,ITEM_CLASS,OBJECT_CLASS),

 /*пока мы не будем разрешать указание одного и того же псевдонима для разных объектов в рамках одного маркета*/
 CONSTRAINT UNIQUE_OF_MARKET_ITEM_SHORT_NAME
  UNIQUE(MARKET_ID,MARKET_CLASS,ITEM_SHORT_NAME,OBJECT_CLASS)
);/*TABLE CRYPTOBOT.MARKETS_ITEMS_NAMES*/

M4_CREATE_TRIGGER_OBJ_DELETE(CRYPTOBOT_MARKETS_ITEMS_NAMES);

M4_REG_TABLE_NAME2(CRYPTOBOT_MARKETS_ITEMS_NAMES,CORE_OBJECTS);

M4_REG_CLASS2(CRYPTOBOT_MARKETS_ITEMS_NAMES,CRYPTOBOT_MARKETS_ITEMS_NAMES,'seq_markets_items_names','Название объекта в рамках биржи');

M4_REG_POS_OBJ_LINKS(CORE_OBJECTS,CRYPTOBOT_MARKETS_ITEMS_NAMES);

M4_CREATE_TRIGGER_RO_OBJ_GUARD(CRYPTOBOT_MARKETS_ITEMS_NAMES);

/* ********************************************************************************************** */
